import shutil
import os

def delete_folder(folder_path):
    shutil.rmtree(folder_path)  # removes the complete folder given at folder path
    print(f"[-] Deleted :{folder_path}")

def main():
    """
    Enter path to the text file generated by `detect_venv.py`
    Then follow on screen instructions to delete the folder or skip them 
    (easy way to restore disk space without deleting project files!)
    """

    search_results_path = input("Enter path to search results by detect_venv.py:")
    if os.path.exists(search_results_path) and os.path.isfile(search_results_path):
        with open(search_results_path, 'r') as results_file:
            for line in results_file:
                name, location = line.strip('\n').split(':')
                print(f"confirm to delete: {name}:{location} ? (y/N): ", end="")
                res = input()
                if res == 'y' or res == 'Y':
                    print("\tDeleting...")
                    delete_folder(location)
                else:
                    print(f"-----skipped-----({name})\n")
    else:
        print("Invalid file location entered, expecting a *.txt file.")
    print(f"{16*'---'}\nThat's all for now!")

if __name__ == "__main__":
    main()